version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: polyglot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: polyglot_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
